export type Product = {
  id: number;
  name: string;
  slug: string;
  sku: string;
  description: string;
  mainCategory: string;
  subcategory: string;
  material?: string;
  threadSize?: string;
  length?: number;
  price: number;
  packSize: number;
  stock: number;
  isNew?: boolean;
  isPromo?: boolean;
  promoPrice?: number;
};

export type CategoryNode = {
  name: string;
  subcategories?: string[];
};

export const CATEGORY_TREE: CategoryNode[] = [
  { name: "Wiertła i frezy", subcategories: ["Do betonu", "Do metalu", "Do drewna", "Uniwersalne i do szkła", "Akcesoria"] },
  { name: "Kołki rozporowe", subcategories: ["Przedłużane", "Uniwersalne", "Standardowe", "Do płyt Gips-Karton", "Specjalne", "Szybki montaż"] },
  { name: "Wkręty i blachowkręty", subcategories: ["Wkręty do Płyt G-K", "Blachowkręty", "Do drewna"] },
  { name: "Kotwy metalowe i chemiczne", subcategories: ["Kotwy do małych obciążeń", "Kotwy do dużych obciążeń", "Do mocowania w płytach", "Do montażu w stropach", "Do mocowania ościeżnic", "Kotwy chemiczne i akcesoria", "Do mocowania rusztowań"] },
  { name: "Dłuta, Koronki, Adaptery", subcategories: ["Dłuta SDS-PLUS", "Dłuta SDS-MAX", "Koronki"] },
  { name: "Dyble Ramowo - Elewacyjne", subcategories: ["Do materiałów otworowych", "Do materiałów pełnych", "Uniwersalne"] },
  { name: "Akcesoria i Narzędzia", subcategories: ["Wkrętaki", "Końcówki wkrętakowe", "Klucze", "Głowice do wiertarki", "Noże i piły", "Inne"] },
  { name: "Ogród" },
  { name: "Opaski kablowe" },
  { name: "Technika diamentowa" },
  { name: "Tarcze i artykuły ścierne" },
  { name: "Gwintowniki, Narzynki, Pokrętła", subcategories: ["Narzynki", "Gwintowniki"] },
];

export const MATERIALS = [
  "Stal nierdzewna A2",
  "Stal nierdzewna A4",
  "Ocynkowany",
  "HSS-Co",
  "HSS",
  "Nylon",
] as const;

export const THREAD_SIZES = ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16"] as const;

export function getEffectivePrice(p: Product): number {
  return p.isPromo && p.promoPrice != null ? p.promoPrice : p.price;
}

export const products: Product[] = [
  // ── Wiertła i frezy – Do betonu ──────────────────────────────────────────
  {
    id: 1,
    name: "Wiertło SDS-Plus do betonu 8×160mm",
    slug: "wiertlo-sds-plus-beton-8x160",
    sku: "WR-SDS-8X160",
    description: "Wiertło udarowe SDS-Plus z węglikiem spiekanym do betonu i muru. Długość robocza 120mm.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do betonu",
    length: 160,
    price: 12.90,
    packSize: 1,
    stock: 245,
    isNew: true,
  },
  {
    id: 2,
    name: "Wiertło SDS-Plus do betonu 10×200mm",
    slug: "wiertlo-sds-plus-beton-10x200",
    sku: "WR-SDS-10X200",
    description: "Długie wiertło udarowe SDS-Plus z węglikiem spiekanym. Spirala 200mm, głębokość montażu 160mm.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do betonu",
    length: 200,
    price: 16.50,
    packSize: 1,
    stock: 180,
  },
  {
    id: 3,
    name: "Wiertło do betonu 6×110mm standardowe",
    slug: "wiertlo-beton-6x110-std",
    sku: "WR-BET-6X110",
    description: "Klasyczne wiertło cylindryczne do betonu i cegły z wkładką węglikową.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do betonu",
    length: 110,
    price: 5.90,
    packSize: 1,
    stock: 520,
  },
  // ── Wiertła i frezy – Do metalu ──────────────────────────────────────────
  {
    id: 4,
    name: "Wiertło HSS-Co do metalu 8mm",
    slug: "wiertlo-hss-co-metal-8",
    sku: "WR-HSS-CO-8",
    description: "Wiertło kobaltowe HSS-Co do stali nierdzewnej i twardych metali. Punkt centrujący, kąt 135°.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do metalu",
    material: "HSS-Co",
    price: 18.90,
    packSize: 1,
    stock: 92,
    isPromo: true,
    promoPrice: 14.90,
  },
  {
    id: 5,
    name: "Wiertło HSS-TiN do metalu 6mm",
    slug: "wiertlo-hss-tin-metal-6",
    sku: "WR-HSS-TIN-6",
    description: "Wiertło do metalu pokryte tytanem TiN, zwiększona twardość i żywotność narzędzia.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do metalu",
    material: "HSS",
    price: 12.50,
    packSize: 1,
    stock: 180,
  },
  {
    id: 6,
    name: "Zestaw wierteł HSS 1–10mm 19szt",
    slug: "zestaw-wiertla-hss-19-szt",
    sku: "WR-HSS-SET-19",
    description: "Kompletny zestaw wierteł HSS co 0.5mm od Ø1 do Ø10mm w metalowej kasecie.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do metalu",
    material: "HSS",
    price: 89.00,
    packSize: 1,
    stock: 34,
    isNew: true,
  },
  // ── Wiertła i frezy – Do drewna ──────────────────────────────────────────
  {
    id: 7,
    name: "Wiertło piórkowe do drewna 25mm",
    slug: "wiertlo-piorowe-drewno-25",
    sku: "WR-PIOR-25",
    description: "Wiertło piórkowe do szybkiego wycinania otworów w drewnie litym, sklejce i MDF.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do drewna",
    price: 7.50,
    packSize: 1,
    stock: 87,
  },
  {
    id: 8,
    name: "Wiertło spiralne do drewna 10×200mm",
    slug: "wiertlo-spiralne-drewno-10x200",
    sku: "WR-SPD-10X200",
    description: "Wiertło spiralne z ostrzem centrującym do drewna litego i materiałów drewnopochodnych.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Do drewna",
    length: 200,
    price: 9.90,
    packSize: 1,
    stock: 145,
  },
  // ── Wiertła i frezy – Uniwersalne i do szkła ─────────────────────────────
  {
    id: 9,
    name: "Wiertło uniwersalne 3-w-1 6mm",
    slug: "wiertlo-uniwersalne-3w1-6",
    sku: "WR-UNI-6",
    description: "Wiertło wielofunkcyjne do betonu, metalu i drewna. Kompatybilne z wiertarką i udarówką.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Uniwersalne i do szkła",
    price: 8.90,
    packSize: 1,
    stock: 230,
    isNew: true,
  },
  {
    id: 10,
    name: "Wiertło do szkła i glazury 6mm",
    slug: "wiertlo-szklo-glazura-6",
    sku: "WR-SZK-6",
    description: "Wiertło z wkładką węglikową do szkła, gresu i ceramiki. Wymaga chłodzenia wodą.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Uniwersalne i do szkła",
    price: 11.50,
    packSize: 1,
    stock: 65,
  },
  // ── Wiertła i frezy – Akcesoria ──────────────────────────────────────────
  {
    id: 11,
    name: "Przedłużacz wierteł SDS-Plus 300mm",
    slug: "przedluzacz-sds-plus-300",
    sku: "AKC-PRZ-SDS-300",
    description: "Adapter-przedłużacz SDS-Plus do wiercenia w trudno dostępnych miejscach. Dł. 300mm.",
    mainCategory: "Wiertła i frezy",
    subcategory: "Akcesoria",
    length: 300,
    price: 34.90,
    packSize: 1,
    stock: 48,
  },
  // ── Kołki rozporowe – Standardowe ────────────────────────────────────────
  {
    id: 12,
    name: "Kołek rozporowy nylonowy UX 8×50mm 100szt",
    slug: "kolek-rozporowy-ux-8x50-100szt",
    sku: "KLK-UX-8X50-100",
    description: "Uniwersalny kołek nylonowy UX do betonu, cegły i muru. Do średnich obciążeń.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Standardowe",
    material: "Nylon",
    threadSize: "M8",
    length: 50,
    price: 19.90,
    packSize: 100,
    stock: 315,
  },
  {
    id: 13,
    name: "Kołek rozporowy S 6×30mm 50szt",
    slug: "kolek-rozporowy-s-6x30-50szt",
    sku: "KLK-S-6X30-50",
    description: "Lekki kołek rozporowy S do betonu i cegły pełnej. Ideał do lekkich montaży.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Standardowe",
    material: "Nylon",
    threadSize: "M6",
    length: 30,
    price: 9.90,
    packSize: 50,
    stock: 480,
  },
  // ── Kołki rozporowe – Uniwersalne ─────────────────────────────────────────
  {
    id: 14,
    name: "Kołek uniwersalny UNI 10×60mm 50szt",
    slug: "kolek-uni-10x60-50szt",
    sku: "KLK-UNI-10X60-50",
    description: "Wielofunkcyjny kołek rozporowy UNI do betonu, cegły pełnej i pustaków.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Uniwersalne",
    material: "Nylon",
    threadSize: "M10",
    length: 60,
    price: 28.90,
    packSize: 50,
    stock: 220,
    isPromo: true,
    promoPrice: 22.90,
  },
  // ── Kołki rozporowe – Do płyt Gips-Karton ────────────────────────────────
  {
    id: 15,
    name: "Kołek motylkowy do GK 13/37mm 50szt",
    slug: "kolek-motylkowy-gk-13x37-50szt",
    sku: "KLK-GK-MOLLY-50",
    description: "Metalowy kołek rozprężny Molly do płyt GK i pustaków. Nośność do 5kg.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Do płyt Gips-Karton",
    material: "Ocynkowany",
    length: 37,
    price: 35.90,
    packSize: 50,
    stock: 130,
    isNew: true,
  },
  {
    id: 16,
    name: "Kołek Toggle Bolt GK 5×60mm 25szt",
    slug: "kolek-toggle-bolt-gk-5x60-25szt",
    sku: "KLK-GK-TGL-25",
    description: "Stalowy kołek skrzydełkowy do płyt GK. Rozkłada obciążenie po drugiej stronie płyty.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Do płyt Gips-Karton",
    material: "Ocynkowany",
    length: 60,
    price: 42.00,
    packSize: 25,
    stock: 85,
  },
  // ── Kołki rozporowe – Szybki montaż ──────────────────────────────────────
  {
    id: 17,
    name: "Kołek szybkiego montażu EasyFix 6×40mm 100szt",
    slug: "kolek-easyfix-6x40-100szt",
    sku: "KLK-EF-6X40-100",
    description: "Kołek z gwoździem do montażu udarowego. Wbijany młotkiem, beton i cegła.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Szybki montaż",
    material: "Ocynkowany",
    length: 40,
    price: 24.90,
    packSize: 100,
    stock: 260,
    isNew: true,
  },
  // ── Kołki rozporowe – Przedłużane ────────────────────────────────────────
  {
    id: 18,
    name: "Kołek przedłużany LP 10×120mm 25szt",
    slug: "kolek-przedluzany-lp-10x120-25szt",
    sku: "KLK-LP-10X120-25",
    description: "Nylonowy kołek rozporowy do montażu przez grubą izolację termiczną. Dł. 120mm.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Przedłużane",
    material: "Nylon",
    threadSize: "M10",
    length: 120,
    price: 39.90,
    packSize: 25,
    stock: 75,
  },
  // ── Kołki rozporowe – Specjalne ───────────────────────────────────────────
  {
    id: 19,
    name: "Kołek do izolacji ISO-T 10×120mm 25szt",
    slug: "kolek-izolacja-iso-t-10x120-25szt",
    sku: "KLK-ISO-10X120-25",
    description: "Specjalistyczny kołek do mocowania izolacji termicznej EPS i wełny mineralnej.",
    mainCategory: "Kołki rozporowe",
    subcategory: "Specjalne",
    material: "Nylon",
    length: 120,
    price: 44.90,
    packSize: 25,
    stock: 92,
  },
  // ── Wkręty i blachowkręty – Wkręty do Płyt G-K ──────────────────────────
  {
    id: 20,
    name: "Wkręt do GK Torx TX15 3,5×35mm 200szt",
    slug: "wkret-gk-torx-tx15-3.5x35-200szt",
    sku: "WKR-GK-TX15-3535",
    description: "Wkręt do płyt gipsowo-kartonowych z łbem wpuszczanym. Napęd Torx TX15.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Wkręty do Płyt G-K",
    material: "Ocynkowany",
    length: 35,
    price: 18.90,
    packSize: 200,
    stock: 520,
    isPromo: true,
    promoPrice: 14.50,
  },
  {
    id: 21,
    name: "Wkręt do GK Phillips 3,5×25mm 500szt",
    slug: "wkret-gk-phillips-3.5x25-500szt",
    sku: "WKR-GK-PH-3525",
    description: "Wkręt do płyt GK z łbem stożkowym i napędem Phillips PH2. Hartowany.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Wkręty do Płyt G-K",
    material: "Ocynkowany",
    length: 25,
    price: 24.90,
    packSize: 500,
    stock: 680,
  },
  // ── Wkręty i blachowkręty – Blachowkręty ─────────────────────────────────
  {
    id: 22,
    name: "Blachowkręt DIN 7981 Hex 4,2×19mm 250szt",
    slug: "blachowkret-din7981-hex-4.2x19-250szt",
    sku: "BLA-DIN7981-HEX-4219",
    description: "Blachowkręt z łbem sześciokątnym i uszczelką EPDM, do pokryć blaszanych.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Blachowkręty",
    material: "Stal nierdzewna A2",
    length: 19,
    price: 32.00,
    packSize: 250,
    stock: 345,
  },
  {
    id: 23,
    name: "Blachowkręt samowiercący 4,8×25mm 100szt",
    slug: "blachowkret-samowiercacy-4.8x25-100szt",
    sku: "BLA-SAM-4825",
    description: "Blachowkręt samowiercący TEK-2 do łączenia blach i profili stalowych.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Blachowkręty",
    material: "Ocynkowany",
    length: 25,
    price: 19.90,
    packSize: 100,
    stock: 415,
  },
  // ── Wkręty i blachowkręty – Do drewna ────────────────────────────────────
  {
    id: 24,
    name: "Wkręt do drewna Torx TX25 5×80mm 100szt",
    slug: "wkret-drewno-torx-5x80-100szt",
    sku: "WKR-D-TX25-5X80",
    description: "Wkręt do drewna z łbem stożkowym i nacięciem. Napęd Torx TX25, ocynk żółty.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Do drewna",
    material: "Ocynkowany",
    length: 80,
    price: 32.00,
    packSize: 100,
    stock: 310,
  },
  {
    id: 25,
    name: "Wkręt do drewna 4×50mm Phillips PH2 200szt",
    slug: "wkret-drewno-4x50-ph2-200szt",
    sku: "WKR-D-PH-4X50",
    description: "Standardowy wkręt do drewna z łbem wpuszczanym i napędem Phillips PH2.",
    mainCategory: "Wkręty i blachowkręty",
    subcategory: "Do drewna",
    material: "Ocynkowany",
    length: 50,
    price: 22.90,
    packSize: 200,
    stock: 560,
  },
  // ── Kotwy metalowe i chemiczne – Kotwy do małych obciążeń ────────────────
  {
    id: 26,
    name: "Kotwa lekka M6×50mm 25szt",
    slug: "kotwa-lekka-m6x50-25szt",
    sku: "KTW-SM-M6X50-25",
    description: "Metalowa kotwa klinowa do lekkich obciążeń w betonie. Gwint zewnętrzny M6.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Kotwy do małych obciążeń",
    material: "Ocynkowany",
    threadSize: "M6",
    length: 50,
    price: 48.00,
    packSize: 25,
    stock: 140,
  },
  {
    id: 27,
    name: "Kołek metalowy KPH 6×60mm 50szt",
    slug: "kolek-metalowy-kph-6x60-50szt",
    sku: "KTW-KPH-6X60-50",
    description: "Stalowy kołek rozporowy KPH do betonu i muru. Ciągłe mufowanie.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Kotwy do małych obciążeń",
    material: "Ocynkowany",
    threadSize: "M6",
    length: 60,
    price: 39.90,
    packSize: 50,
    stock: 205,
  },
  // ── Kotwy metalowe i chemiczne – Kotwy do dużych obciążeń ────────────────
  {
    id: 28,
    name: "Kotwa rozprężna HST3 M12×90mm 10szt",
    slug: "kotwa-hst3-m12x90-10szt",
    sku: "KTW-HST3-M12X90-10",
    description: "Ciężka kotwa mechaniczna do betonu z aprobatą ETA. Nośność charakterystyczna ~30kN.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Kotwy do dużych obciążeń",
    material: "Stal nierdzewna A4",
    threadSize: "M12",
    length: 90,
    price: 124.00,
    packSize: 10,
    stock: 45,
    isNew: true,
  },
  // ── Kotwy metalowe i chemiczne – Do mocowania ościeżnic ──────────────────
  {
    id: 29,
    name: "Kotwa ramowa FNA II 10/100 10szt",
    slug: "kotwa-ramowa-fna-10x100-10szt",
    sku: "KTW-FNA-10X100-10",
    description: "Kołek ramowy do montażu okien i drzwi w betonie i cegle. Śruba z łbem Hex.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Do mocowania ościeżnic",
    material: "Ocynkowany",
    length: 100,
    price: 48.00,
    packSize: 10,
    stock: 88,
  },
  // ── Kotwy metalowe i chemiczne – Kotwy chemiczne i akcesoria ─────────────
  {
    id: 30,
    name: "Kotwa chemiczna epoksydowa HIT-RE 300ml",
    slug: "kotwa-chemiczna-ep-hre-300ml",
    sku: "KTW-CHEM-EP-300",
    description: "Dwuskładnikowa kotwa epoksydowa do betonu, cegły i betonu spękanego. V4.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Kotwy chemiczne i akcesoria",
    price: 89.00,
    packSize: 1,
    stock: 62,
    isNew: true,
  },
  {
    id: 31,
    name: "Zestaw głowic do kotew chemicznych 10szt",
    slug: "zestaw-glowic-kotwy-chemiczne-10szt",
    sku: "AKC-GLOW-CHEM-10",
    description: "Zestaw plastikowych perforowanych tulei iniekcyjnych do kotew chemicznych.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Kotwy chemiczne i akcesoria",
    price: 24.90,
    packSize: 10,
    stock: 95,
  },
  // ── Kotwy metalowe i chemiczne – Do mocowania w płytach ──────────────────
  {
    id: 32,
    name: "Kotwa do płyt GK Metal Toggle 6×25mm 50szt",
    slug: "kotwa-gk-metal-toggle-6x25-50szt",
    sku: "KTW-PLYTA-MT-6X25-50",
    description: "Metalowa kotwa rozprężna do płyt GK i pustaków. Nośność osiowa do 8kg.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Do mocowania w płytach",
    material: "Ocynkowany",
    threadSize: "M6",
    length: 25,
    price: 44.90,
    packSize: 50,
    stock: 125,
  },
  // ── Kotwy metalowe i chemiczne – Do montażu w stropach ───────────────────
  {
    id: 33,
    name: "Kotwa do stropu WB-T M8×45mm 25szt",
    slug: "kotwa-strp-wbt-m8x45-25szt",
    sku: "KTW-STRP-WBT-M8X45-25",
    description: "Kotwa do zawieszenia instalacji na stropie betonowym z gwintem M8. Aprobata AT.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Do montażu w stropach",
    material: "Ocynkowany",
    threadSize: "M8",
    length: 45,
    price: 68.00,
    packSize: 25,
    stock: 55,
  },
  // ── Kotwy metalowe i chemiczne – Do mocowania rusztowań ──────────────────
  {
    id: 34,
    name: "Kotwa do rusztowań HDA-T M16 ciężka 10szt",
    slug: "kotwa-rusztowanie-hdat-m16-10szt",
    sku: "KTW-RUSZT-M16-10",
    description: "Ciężka kotwa dociskowa do rusztowań w betonie. Śruba M16, nośność ponad 50kN.",
    mainCategory: "Kotwy metalowe i chemiczne",
    subcategory: "Do mocowania rusztowań",
    material: "Stal nierdzewna A4",
    threadSize: "M16",
    price: 185.00,
    packSize: 10,
    stock: 28,
  },
  // ── Dłuta, Koronki, Adaptery – Dłuta SDS-PLUS ───────────────────────────
  {
    id: 35,
    name: "Dłuto płaskie SDS-Plus 20×250mm",
    slug: "dluto-plaskie-sds-plus-20x250",
    sku: "DLU-SDSP-PLK-20X250",
    description: "Dłuto płaskie SDS-Plus do skuwania tynku, glazury i betonu. Szer. ostrza 20mm.",
    mainCategory: "Dłuta, Koronki, Adaptery",
    subcategory: "Dłuta SDS-PLUS",
    length: 250,
    price: 28.90,
    packSize: 1,
    stock: 110,
    isPromo: true,
    promoPrice: 22.90,
  },
  {
    id: 36,
    name: "Dłuto punktowe SDS-Plus 250mm",
    slug: "dluto-punktowe-sds-plus-250",
    sku: "DLU-SDSP-PKT-250",
    description: "Dłuto punktowe do rozbijania betonu i kamienia. Uchwyt SDS-Plus, dł. 250mm.",
    mainCategory: "Dłuta, Koronki, Adaptery",
    subcategory: "Dłuta SDS-PLUS",
    length: 250,
    price: 24.90,
    packSize: 1,
    stock: 80,
  },
  // ── Dłuta, Koronki, Adaptery – Dłuta SDS-MAX ────────────────────────────
  {
    id: 37,
    name: "Dłuto płaskie SDS-Max 25×400mm",
    slug: "dluto-plaskie-sds-max-25x400",
    sku: "DLU-SDSM-PLK-25X400",
    description: "Duże dłuto płaskie SDS-Max do prac wyburzeniowych i skuwania posadzek.",
    mainCategory: "Dłuta, Koronki, Adaptery",
    subcategory: "Dłuta SDS-MAX",
    length: 400,
    price: 68.00,
    packSize: 1,
    stock: 40,
  },
  // ── Dłuta, Koronki, Adaptery – Koronki ──────────────────────────────────
  {
    id: 38,
    name: "Koronka diamentowa do glazury 68mm",
    slug: "koronka-diamentowa-glazura-68",
    sku: "KOR-DIA-68",
    description: "Koronka wiertnicza z segmentem diamentowym do gresu, glazury i kamienia.",
    mainCategory: "Dłuta, Koronki, Adaptery",
    subcategory: "Koronki",
    price: 45.00,
    packSize: 1,
    stock: 72,
    isNew: true,
  },
  {
    id: 39,
    name: "Koronka bi-metalowa do drewna 57mm",
    slug: "koronka-bimetalowa-drewno-57",
    sku: "KOR-BIM-57",
    description: "Koronka bi-metalowa do wycinania otworów w drewnie, meblach i tworzywach sztucznych.",
    mainCategory: "Dłuta, Koronki, Adaptery",
    subcategory: "Koronki",
    price: 29.90,
    packSize: 1,
    stock: 55,
  },
  // ── Dyble Ramowo - Elewacyjne – Do materiałów otworowych ─────────────────
  {
    id: 40,
    name: "Dybel elewacyjny FID 8×40mm do pustaków 25szt",
    slug: "dybel-elewacyjny-fid-8x40-25szt",
    sku: "DYB-FID-8X40-25",
    description: "Dybel ramowy do materiałów otworowych: pustaki, cegła dziurawka. Korpus nylonowy.",
    mainCategory: "Dyble Ramowo - Elewacyjne",
    subcategory: "Do materiałów otworowych",
    material: "Nylon",
    length: 40,
    price: 42.00,
    packSize: 25,
    stock: 98,
  },
  // ── Dyble Ramowo - Elewacyjne – Do materiałów pełnych ────────────────────
  {
    id: 41,
    name: "Dybel do betonu FBN II 8/40 25szt",
    slug: "dybel-beton-fbn-8x40-25szt",
    sku: "DYB-FBN-8X40-25",
    description: "Metalowy dybel ramowy samonawiercający do betonu i cegły pełnej.",
    mainCategory: "Dyble Ramowo - Elewacyjne",
    subcategory: "Do materiałów pełnych",
    material: "Ocynkowany",
    length: 40,
    price: 58.00,
    packSize: 25,
    stock: 65,
  },
  // ── Dyble Ramowo - Elewacyjne – Uniwersalne ──────────────────────────────
  {
    id: 42,
    name: "Dybel ramowy FNA 10/100 10szt",
    slug: "dybel-ramowy-fna-10x100-10szt",
    sku: "DYB-FNA-10X100-10",
    description: "Uniwersalny dybel ramowy do betonu, cegły i pustaków. Do montażu okien i drzwi.",
    mainCategory: "Dyble Ramowo - Elewacyjne",
    subcategory: "Uniwersalne",
    material: "Ocynkowany",
    length: 100,
    price: 52.00,
    packSize: 10,
    stock: 78,
  },
  // ── Akcesoria i Narzędzia – Końcówki wkrętakowe ──────────────────────────
  {
    id: 43,
    name: "Zestaw końcówek wkrętakowych 32szt TX/PH/PZ",
    slug: "zestaw-konce-wkretakowe-32szt",
    sku: "AKC-KWK-SET-32",
    description: "32 końcówki wkrętakowe 25mm: Torx, Phillips, Pozidriv i płaskie, w kasecie.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Końcówki wkrętakowe",
    material: "HSS",
    price: 39.90,
    packSize: 1,
    stock: 125,
    isNew: true,
    isPromo: true,
    promoPrice: 29.90,
  },
  {
    id: 44,
    name: "Końcówka Torx TX30 25mm 10szt",
    slug: "konc-torx-tx30-25mm-10szt",
    sku: "AKC-KWK-TX30-10",
    description: "Końcówka wkrętakowa Torx TX30, dł. 25mm, stal S2. Do wkrętarek akumulatorowych.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Końcówki wkrętakowe",
    price: 12.90,
    packSize: 10,
    stock: 210,
  },
  // ── Akcesoria i Narzędzia – Klucze ───────────────────────────────────────
  {
    id: 45,
    name: "Klucz nasadowy 13mm 1/2\" CrV",
    slug: "klucz-nasadowy-13mm-1-2",
    sku: "AKC-KLU-13-12",
    description: "Klucz nasadowy 13mm do napędu 1/2\". Chrom-wanad, hartowany indukcyjnie.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Klucze",
    price: 18.90,
    packSize: 1,
    stock: 89,
  },
  // ── Akcesoria i Narzędzia – Wkrętaki ─────────────────────────────────────
  {
    id: 46,
    name: "Wkrętak elektryczny 3,6V Li-Ion",
    slug: "wkretak-el-3-6v-li-ion",
    sku: "AKC-WKR-36V",
    description: "Kompaktowy wkrętak akumulatorowy 3.6V z uchwytem 1/4\" i zestawem 20 bitów.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Wkrętaki",
    price: 149.00,
    packSize: 1,
    stock: 35,
    isNew: true,
  },
  // ── Akcesoria i Narzędzia – Głowice do wiertarki ─────────────────────────
  {
    id: 47,
    name: "Głowica kątowa do wiertarki 90°",
    slug: "glowica-katowa-wiertarka-90",
    sku: "AKC-GLW-KAT-90",
    description: "Adapter kątowy 90° do wiertarki. Napęd wejściowy 10mm, uchwyt wiertarski 10mm.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Głowice do wiertarki",
    price: 89.00,
    packSize: 1,
    stock: 28,
  },
  // ── Akcesoria i Narzędzia – Noże i piły ──────────────────────────────────
  {
    id: 48,
    name: "Brzeszczot do metalu HCS 300mm 5szt",
    slug: "brzeszczot-metal-hcs-300mm-5szt",
    sku: "AKC-BRZ-HCS-300-5",
    description: "Brzeszczot do piły do metalu HCS, 300mm, 24 TPI. Do cięcia profili stalowych.",
    mainCategory: "Akcesoria i Narzędzia",
    subcategory: "Noże i piły",
    material: "HSS",
    length: 300,
    price: 24.90,
    packSize: 5,
    stock: 68,
    isPromo: true,
    promoPrice: 18.90,
  },
  // ── Ogród ──────────────────────────────────────────────────────────────────
  {
    id: 49,
    name: "Wkręt tarasowy TX25 5×60mm 200szt A2",
    slug: "wkret-tarasowy-tx25-5x60-200szt",
    sku: "OGR-WKR-TAR-5X60",
    description: "Wkręt do drewna tarasowego ze stali nierdzewnej A2. Łeb TX25, odporny na korozję.",
    mainCategory: "Ogród",
    subcategory: "Ogród",
    material: "Stal nierdzewna A2",
    length: 60,
    price: 68.00,
    packSize: 200,
    stock: 145,
  },
  {
    id: 50,
    name: "Kołek gruntowy stalowy 150mm 10szt",
    slug: "kolek-gruntowy-stalowy-150-10szt",
    sku: "OGR-KLK-GRN-150-10",
    description: "Stalowy kołek do gruntu do mocowania siatek, mat ogrodowych i ogrodzenia.",
    mainCategory: "Ogród",
    subcategory: "Ogród",
    material: "Ocynkowany",
    length: 150,
    price: 35.90,
    packSize: 10,
    stock: 82,
    isNew: true,
  },
  // ── Opaski kablowe ────────────────────────────────────────────────────────
  {
    id: 51,
    name: "Opaski kablowe UV białe 3,6×200mm 100szt",
    slug: "opaski-kablowe-uv-biale-3.6x200-100szt",
    sku: "OPA-UV-B-36X200",
    description: "Nylonowe opaski zaciskowe UV do instalacji zewnętrznych. Szer. 3.6mm, dł. 200mm.",
    mainCategory: "Opaski kablowe",
    subcategory: "Opaski kablowe",
    material: "Nylon",
    length: 200,
    price: 8.90,
    packSize: 100,
    stock: 420,
  },
  {
    id: 52,
    name: "Opaski kablowe czarne 4,8×300mm 50szt",
    slug: "opaski-kablowe-czarne-4.8x300-50szt",
    sku: "OPA-CZ-48X300",
    description: "Nylonowe opaski zaciskowe czarne do instalacji elektrycznych. Szer. 4.8mm, dł. 300mm.",
    mainCategory: "Opaski kablowe",
    subcategory: "Opaski kablowe",
    material: "Nylon",
    length: 300,
    price: 12.90,
    packSize: 50,
    stock: 310,
  },
  // ── Technika diamentowa ───────────────────────────────────────────────────
  {
    id: 53,
    name: "Tarcza diamentowa Turbo 125mm do betonu",
    slug: "tarcza-diamentowa-125-beton",
    sku: "TDM-TAR-125-BET",
    description: "Turbo tarcza diamentowa do cięcia na sucho betonu, betonu komórkowego i kamienia.",
    mainCategory: "Technika diamentowa",
    subcategory: "Technika diamentowa",
    price: 34.90,
    packSize: 1,
    stock: 88,
    isPromo: true,
    promoPrice: 27.90,
  },
  {
    id: 54,
    name: "Koronka diamentowa 68mm wiercenie mokre",
    slug: "koronka-diamentowa-68-mokre",
    sku: "TDM-WRT-DIA-68",
    description: "Segmentowa koronka diamentowa do wiercenia na mokro w betonie i żelbecie. Gwint M16.",
    mainCategory: "Technika diamentowa",
    subcategory: "Technika diamentowa",
    price: 89.00,
    packSize: 1,
    stock: 32,
  },
  // ── Tarcze i artykuły ścierne ─────────────────────────────────────────────
  {
    id: 55,
    name: "Tarcza fibrowa 125mm P60 25szt",
    slug: "tarcza-fibrowa-125-p60-25szt",
    sku: "SCR-TAR-FIB-P60-25",
    description: "Tarcza ścierna fibrowa 125mm, granulacja P60. Do szlifowania metalu i drewna na kątówce.",
    mainCategory: "Tarcze i artykuły ścierne",
    subcategory: "Tarcze i artykuły ścierne",
    price: 42.00,
    packSize: 25,
    stock: 210,
  },
  {
    id: 56,
    name: "Tarcza szlifierska 115mm P80 10szt",
    slug: "tarcza-szlif-115-p80-10szt",
    sku: "SCR-TAR-SZL-P80-10",
    description: "Tarcza szlifierska fibrowa 115mm, granulacja P80. Do szlifowania powierzchni metalowych.",
    mainCategory: "Tarcze i artykuły ścierne",
    subcategory: "Tarcze i artykuły ścierne",
    price: 18.90,
    packSize: 10,
    stock: 155,
    isNew: true,
  },
  // ── Gwintowniki, Narzynki, Pokrętła – Narzynki ───────────────────────────
  {
    id: 57,
    name: "Narzynka M8 HSS DIN 223",
    slug: "narzynka-m8-hss-din223",
    sku: "GWT-NAR-M8-HSS",
    description: "Narzynka okrągła M8 HSS do nacinania gwintu zewnętrznego. Norma DIN 223.",
    mainCategory: "Gwintowniki, Narzynki, Pokrętła",
    subcategory: "Narzynki",
    material: "HSS",
    threadSize: "M8",
    price: 18.90,
    packSize: 1,
    stock: 92,
  },
  {
    id: 58,
    name: "Zestaw narzynek M3–M12 9szt HSS",
    slug: "zestaw-narzynek-m3-m12-9szt",
    sku: "GWT-NAR-SET-9",
    description: "Zestaw 9 narzynek okrągłych HSS M3 do M12 w metalowej kasecie.",
    mainCategory: "Gwintowniki, Narzynki, Pokrętła",
    subcategory: "Narzynki",
    material: "HSS",
    price: 89.00,
    packSize: 1,
    stock: 38,
  },
  // ── Gwintowniki, Narzynki, Pokrętła – Gwintowniki ────────────────────────
  {
    id: 59,
    name: "Gwintownik maszynowy M10 HSS",
    slug: "gwintownik-maszynowy-m10-hss",
    sku: "GWT-GWN-M10-HSS",
    description: "Gwintownik maszynowy M10 HSS do nacinania gwintu wewnętrznego. Chwyt walcowy.",
    mainCategory: "Gwintowniki, Narzynki, Pokrętła",
    subcategory: "Gwintowniki",
    material: "HSS",
    threadSize: "M10",
    price: 24.90,
    packSize: 1,
    stock: 55,
    isNew: true,
  },
  {
    id: 60,
    name: "Zestaw gwintowników M3–M12 6szt HSS",
    slug: "zestaw-gwintownikow-m3-m12-6szt",
    sku: "GWT-GWN-SET-6",
    description: "Komplet 6 gwintowników maszynowych HSS M3, M4, M5, M6, M8, M10 w kasecie.",
    mainCategory: "Gwintowniki, Narzynki, Pokrętła",
    subcategory: "Gwintowniki",
    material: "HSS",
    price: 68.00,
    packSize: 1,
    stock: 42,
    isPromo: true,
    promoPrice: 54.90,
  },
];
